### ISSUE TITLE
update setup.cfg 

### ISSUE THREAD

**Issue by Louw123** [irmen/binaryen-interfaces#6]
_DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      /Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/gv/zls9_j1d1hs0pg41g7vt02sr0000gn/T/pip-install-29xmliz0/pybinaryen_c059253132e24a45bc6d623270046ac2/setup.py", line 18, in <module>
          setup(
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 674, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/installer.py", line 106, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/wheel.py", line 120, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/wheel.py", line 128, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/wheel.py", line 173, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/gv/zls9_j1d1hs0pg41g7vt02sr0000gn/T/pip-install-29xmliz0/pybinaryen_c059253132e24a45bc6d623270046ac2/.eggs/cffi-1.16.0-py3.11-macosx-10.9-universal2.egg/cffi-1.16.0.dist-info' -> '/private/var/folders/gv/zls9_j1d1hs0pg41g7vt02sr0000gn/T/pip-install-29xmliz0/pybinaryen_c059253132e24a45bc6d623270046ac2/.eggs/cffi-1.16.0-py3.11-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pybinaryen
  Running setup.py clean for pybinaryen
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      /Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/gv/zls9_j1d1hs0pg41g7vt02sr0000gn/T/pip-install-29xmliz0/pybinaryen_c059253132e24a45bc6d623270046ac2/setup.py", line 18, in <module>
          setup(
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 674, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/installer.py", line 106, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/wheel.py", line 120, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/wheel.py", line 128, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/wheel.py", line 173, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/gv/zls9_j1d1hs0pg41g7vt02sr0000gn/T/pip-install-29xmliz0/pybinaryen_c059253132e24a45bc6d623270046ac2/.eggs/cffi-1.16.0-py3.11-macosx-10.9-universal2.egg/cffi-1.16.0.dist-info' -> '/private/var/folders/gv/zls9_j1d1hs0pg41g7vt02sr0000gn/T/pip-install-29xmliz0/pybinaryen_c059253132e24a45bc6d623270046ac2/.eggs/cffi-1.16.0-py3.11-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pybinaryen
Failed to build pybinaryen
ERROR: Could not build wheels for pybinaryen, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
(.venv) louismcmaster@MacBook-Pro-Louis pythonProject1 % sudo pip install pybinaryen
Password:
WARNING: The directory '/Users/louismcmaster/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting pybinaryen
  Downloading pybinaryen-1.112.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting cffi>=1.3.0 (from pybinaryen)
  Obtaining dependency information for cffi>=1.3.0 from https://files.pythonhosted.org/packages/18/6c/0406611f3d5aadf4c5b08f6c095d874aed8dfc2d3a19892707d72536d5dc/cffi-1.16.0-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Downloading cffi-1.16.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi>=1.3.0->pybinaryen)
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 1.5 MB/s eta 0:00:00
Downloading cffi-1.16.0-cp311-cp311-macosx_11_0_arm64.whl (176 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.7/176.7 kB 4.7 MB/s eta 0:00:00
Building wheels for collected packages: pybinaryen
  Building wheel for pybinaryen (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      /Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      /Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      WARNING: The directory '/Users/louismcmaster/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/tmp/pip-install-wk1gx81y/pybinaryen_ebd6a6073bd74c8aabd32dbd53056a32/setup.py", line 18, in <module>
          setup(
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 674, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/installer.py", line 106, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/wheel.py", line 120, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/wheel.py", line 128, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/wheel.py", line 173, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/tmp/pip-install-wk1gx81y/pybinaryen_ebd6a6073bd74c8aabd32dbd53056a32/.eggs/cffi-1.16.0-py3.11-macosx-10.9-universal2.egg/cffi-1.16.0.dist-info' -> '/private/tmp/pip-install-wk1gx81y/pybinaryen_ebd6a6073bd74c8aabd32dbd53056a32/.eggs/cffi-1.16.0-py3.11-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pybinaryen
  Running setup.py clean for pybinaryen
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      /Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      /Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      WARNING: The directory '/Users/louismcmaster/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/tmp/pip-install-wk1gx81y/pybinaryen_ebd6a6073bd74c8aabd32dbd53056a32/setup.py", line 18, in <module>
          setup(
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 674, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/installer.py", line 106, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/wheel.py", line 120, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/wheel.py", line 128, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/louismcmaster/PycharmProjects/pythonProject1/.venv/lib/python3.11/site-packages/setuptools/wheel.py", line 173, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/tmp/pip-install-wk1gx81y/pybinaryen_ebd6a6073bd74c8aabd32dbd53056a32/.eggs/cffi-1.16.0-py3.11-macosx-10.9-universal2.egg/cffi-1.16.0.dist-info' -> '/private/tmp/pip-install-wk1gx81y/pybinaryen_ebd6a6073bd74c8aabd32dbd53056a32/.eggs/cffi-1.16.0-py3.11-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]

**Comment by irmen** [comment]
fixed in #7 I guess?
